# Generated by Django 5.1.4 on 2024-12-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listitime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('date1', models.CharField(max_length=100)),
                ('course1', models.CharField(max_length=100)),
            ],
        ),
    ]
